FileSharing/FileSharing/Controllers/AdvertisingController.cs
using FileSharing.AdvertisingService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileSharing.Controllers
{
    public class AdvertisingController : Controller
    {

        //GET: Spam
        public ActionResult Index()
        {
            return PartialView();
        }

        public FileContentResult GetImage()
        {
            SpamServiceClient spamClient = new SpamServiceClient();

            var spam = spamClient.GetAdvertising();

            if(spam != null)
            {
                return File(spam.Image, spam.TypeImage);
            }

            return null;
        }
    }
}

FileSharing/FileSharing/Controllers/CategoryController.cs
using PagedList;
using PagedList.Mvc;
using FileSharing.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileSharing.Entities.Core;
using FileSharing.Business.Interfaces;
using FileSharing.Entities.Logging;

namespace FileSharing.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IBusinessLogic _bl;

        private const int PAGE_SIZE = 2;

        public CategoryController(IBusinessLogic bl)
        {
            _bl = bl;
        }

        // GET: Category
        [AdminModer]
        public ActionResult ListOfCategories(int? page, string categoryName)
        {
            int pageNumber = (page ?? 1);

            var categories = _bl.Categories.GetAll();

            return View(categories.ToPagedList(pageNumber, PAGE_SIZE));
        }

        [AdminModer]
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View(new Category());
        }

        [AdminModer]
        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _bl.Categories.Create(category);

                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [AdminModer]
        [HttpGet]
        public ActionResult EditCategory(int? id)
        {
            if (id == null)
            {
                Logger.Log.Error("EditCategory - id == null");
                return HttpNotFound();
            }

            var category = _bl.Categories.GetItemById(id);

            if (category == null)
            {
                Logger.Log.Error("EditCategory - category not found");
                return HttpNotFound();
            }

            return View(category);
        }

        [AdminModer]
        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _bl.Categories.Update(category);

                return RedirectToAction("ListOfCategories");
            }
            return View(category);
        }

        [AdminModer]
        public ActionResult DeleteCategory(int? id)
        {
            if (id == null)
            {
                Logger.Log.Error("DeleteCategory - id == null");

                return HttpNotFound();
            }

            var category = _bl.Categories.GetItemById(id);

            if (category == null)
            {
                Logger.Log.Error("DeleteCategory - category not found");

                return HttpNotFound();
            }

            var files = _bl.Files.GetAll();

            bool exist = false;

            foreach(var file in files)
            {
                if(file.CategoryId == category.Id)
                {
                    exist = true;
                    break;
                }
            }

            if (exist)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                _bl.Categories.Delete(category);
            }
            return RedirectToAction("ListOfCategories");
        }
    }
}

FileSharing/FileSharing/Controllers/FileController.cs
using PagedList;
using PagedList.Mvc;
using FileSharing.Entities.Core;
using FileSharing.Entities.Models;
using FileSharing.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileSharing.Business.Interfaces;
using FileSharing.Entities.Logging;

namespace FileSharing.Controllers
{
    public class FileController : Controller
    {
        private readonly IBusinessLogic _bl;

        private const int PAGE_SIZE = 2;

        public FileController(IBusinessLogic bl)
        {
            _bl = bl;
        }

        // GET: File
        [HttpGet]
        public ActionResult Index(int? page, string category, string expansion, string fileName, string access)
        {
            var categoryListDb = GetListCategories();

            List<string> categoryList = new List<string>()
            {
                "Выбрать категорию"
            };

            foreach(var dbCategory in categoryListDb)
            {
                categoryList.Add(dbCategory);
            }

            ViewBag.Categories = new SelectList(categoryList);

            var expansionListDb = GetListExpansions();

            List<string> expansionList = new List<string>()
            {
                "Выбрать расширение"
            };

            foreach(var dbExpansion in expansionListDb)
            {
                expansionList.Add(dbExpansion);
            }

            ViewBag.Expansions = new SelectList(expansionList);

            var accessListDb = GetListAccesses();

            List<string> accessList = new List<string>
            {
                "Выбрать доступ к файлу"
            };

            foreach(var dbAccess in accessListDb)
            {
                accessList.Add(dbAccess);
            }

            ViewBag.Accesses = new SelectList(accessList);

            int pageNumber = (page ?? 1);
            var files = _bl.Files.GetAll();

            if (fileName != "" && fileName != null)
            {
                files = files.Where(m => m.Name.Contains(fileName));
            }

            if (category != null && category != "Выбрать категорию")
            {
                var objCategory = _bl.Categories.GetElement(new Category { Name = category });

                files = files.Where(m => m.CategoryId == objCategory.Id);
            }


            var selectedFiles = new List<File>();

            if(expansion != null && expansion != "Выбрать расширение")
            {
                foreach (var file in files)
                {
                    var splitName = file.Name.Split('.');

                    if (splitName[splitName.Length - 1] == expansion)
                    {
                        selectedFiles.Add(file);
                    }
                }
            }
            else
            {
                selectedFiles = files.ToList();
            }

            var models = new List<IndexFileViewModel>();

            foreach(var file in selectedFiles)
            {
                var user = _bl.Users.GetItemById(file.UserId);

                models.Add(new IndexFileViewModel()
                {
                    Id = file.Id,
                    UserId = file.UserId,
                    FileAccessId = file.FileAccessId,
                    Name = file.Name,
                    UserLogin = user.Login,
                    Description = file.Description,
                    Size = Math.Round(file.Size, 2),
                    DownloadDate = file.DownloadDate
                });
            }

            return View(models.ToPagedList(pageNumber, PAGE_SIZE));
        }

        private List<string> GetListAccesses()
        {
            var accesses = _bl.FileAccesses.GetAll();

            var list = new List<string>();

            foreach(var access in accesses)
            {
                list.Add(access.Name);
            }

            return list;
        }

        private List<string> GetListExpansions()
        {
            var files = _bl.Files.GetAll();

            var list = new List<string>();

            foreach(var file in files)
            {
                var splitName = file.Name.Split('.');

                if(!list.Contains(splitName[splitName.Length - 1]))
                {
                    list.Add(splitName[splitName.Length - 1]);
                }
            }

            return list;
        }

        private List<string> GetListCategories()
        {
            var categories = _bl.Categories.GetAll();

            var list = new List<string>();

            foreach (var category in categories)
            {
                list.Add(category.Name);
            }

            return list;
        }

        #region Загрузка файлов 
        
        //GET: File/Upload
        [Auth]
        [HttpGet]
        public ActionResult Upload()
        {
            ViewBag.Categories = new SelectList(GetListCategories());

            return View(new UploadFileViewModel() { IsPublic = true });
        }

        //POST: File/Upload       
        [Auth]
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload, UploadFileViewModel file)
        {
            if(upload != null)
            {
                var files = Request.Files;

                string fileName = System.IO.Path.GetFileName(upload.FileName);

                var fileModel = new File
                {
                    UserId = Convert.ToInt32(HttpContext.Request.Cookies["Id"].Value),
                    Name = fileName,
                    Description = file.Description,
                    DownloadDate = DateTime.Now
                };

                if(file.Description == null)
                {
                    fileModel.Description = "";
                }

                var category = _bl.Categories.GetElement(new Category { Name = file.Category });

                if(category != null)
                {
                    fileModel.CategoryId = category.Id;
                }

                int size = upload.ContentLength;

                fileModel.Size = Math.Round(((double)size) / 1048576, 2);

                //fileModel.Url = "~/App_Data/" + fileName;

                _bl.Files.Create(fileModel);

                //upload.SaveAs(Server.MapPath(fileModel.Url));

                return RedirectToAction("ListOfUserFiles");
            }
            else
            {
                ModelState.AddModelError("", "Файл не найден");
            }
            return View(file);
        }

        #endregion

        public ActionResult Download(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var file = _bl.Files.GetItemById(id);            

            if (file == null)
            {
                Logger.Log.Error("Download - file not found");
                return HttpNotFound();
            }

            var fileUrl = _bl.FileUrls.GetItemById(file.FileUrlId);

            string[] splitFullName = (file.Name).Split('.');

            string typeFile = "application/" + splitFullName[splitFullName.Length - 1];
            return File(Server.MapPath(fileUrl.Url), typeFile, file.Name);
        }

        [Auth]
        public ActionResult ListOfUserFiles(int? id)
        {
            var files = _bl.Files.GetAll();

            if (id == null)
            {
                id = Convert.ToInt32(HttpContext.Request.Cookies["Id"].Value);
            }

            var fileAccess = _bl.FileAccesses.GetAll().Where(x => x.Name == "Общедоступный").FirstOrDefault();

            files = files.Where(m => m.UserId == id);

            if (Request.Cookies["Admin"] == null && Request.Cookies["Moder"] == null && Request.Cookies["Id"].Value != id.ToString())
            {
                files = files.Where(m => m.FileAccessId == fileAccess.Id);
            }

            return View(files);
        }

        [Auth]
        [HttpGet]
        public ActionResult EditFile(int? id)
        {
            ViewBag.Categories = new SelectList(GetListCategories());

            var file = _bl.Files.GetItemById(id);

            if (file == null)
            {
                Logger.Log.Error("EditFile - file not found");

                return HttpNotFound();
            }

            var fileAccesses = _bl.FileAccesses.GetAll();

            ViewBag.FileAccesses = fileAccesses;

            var fileAccess = fileAccesses.Where(x => x.Id == file.FileAccessId).FirstOrDefault();

            var category = _bl.Categories.GetItemById(file.CategoryId);

            var model = new EditFileViewModel()
            {
                Id = file.Id,
                Name = file.Name,
                Category = category.Name,
                Description = file.Description,
                Access = fileAccess.Name
            };

            return View(model);
        }

        [Auth]
        [HttpPost]
        public ActionResult EditFile(EditFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = _bl.Files.GetItemById(model.Id);

                if (file == null)
                {
                    Logger.Log.Error("EditFile - file not found");

                    return HttpNotFound();
                }

                var category = _bl.Categories.GetElement(new Category { Name = model.Category });

                var fileAccess = _bl.FileAccesses.GetAll().Where(x => x.Name == model.Name).FirstOrDefault();

                file.CategoryId = category.Id;
                file.Description = model.Description;
                file.FileAccessId = fileAccess.Id;

                _bl.Files.Update(file);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Auth]
        public ActionResult DeleteFile(int? id)
        {
            var file = _bl.Files.GetItemById(id);

FileSharing/FileSharing/Views/Shared/_Admin.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
    <li>@Html.ActionLink("Загрузить", "Upload", "File")</li>
    <li>@Html.ActionLink("Скачать", "Download", "File")</li>
    <li>@Html.ActionLink("О сайте", "About", "Home")</li>
    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
    <li class="nav-item dropdown">
        <a class="navbar-link dropdown-toggle" href="#" id="navbarDropdownMenuListLink" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Списки
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>@Html.ActionLink("Список пользователей", "ListOfUsers", "Manage")</li>
            <li>@Html.ActionLink("Список файлов", "Index", "File")</li>
            <li>@Html.ActionLink("Список категорий", "ListOfCategories", "Category")</li>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="navbar-link dropdown-toggle" href="#" id="navbarDropdownMenuAddLink" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Добавить
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>@Html.ActionLink("Пользователя", "AddUser", "Manage")</li>
            <li>@Html.ActionLink("Файл", "Upload", "File")</li>
            <li>@Html.ActionLink("Категорию", "AddCategory", "Category")</li>
        </ul>
    </li>
</ul>

@using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Мой аккаунт", "AccountIndex", "Manage")</li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
}

FileSharing/FileSharing/Views/Shared/_Guest.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
    <li>@Html.ActionLink("Загрузить", "Upload", "File")</li>
    <li>@Html.ActionLink("Скачать", "Download", "File")</li>
    <li>@Html.ActionLink("О сайте", "About", "Home")</li>
    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
</ul>

<ul class="nav navbar-nav navbar-right">
    <li>@Html.ActionLink("Вход", "Login", "Account")</li>
    <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
</ul>

FileSharing/FileSharing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background:url(../../Content/img/backGroundNav.png)">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Brand", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*Для зарегистрированных пользователей*@
                @if (Request.Cookies["Id"] != null)
                {
                    if (Request.Cookies["User"] != null)
                    {
                        Html.RenderPartial("_User");
                    }

                    if (Request.Cookies["Admin"] != null)
                    {
                        Html.RenderPartial("_Admin");
                    }

                    if (Request.Cookies["Moder"] != null)
                    {
                        Html.RenderPartial("_Moder");
                    }
                }
                else
                {
                    @*Для незарегистрированных пользователей*@
                    Html.RenderPartial("_Guest");
                }
                @if (Request.Cookies["Admin"] == null && Request.Cookies["Moder"] == null)
                {
                    using (Html.BeginForm("Index", "File", FormMethod.Get, new { @class = "navbar-form navbar-left", @role = "search" }))
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" name="fileName" placeholder="Search">
                        </div>
                        <input type="submit" class="btn btn-default" value="Поиск">
                    }
                }


            </div>
        </div>
    </div>
    <div class="container-fluid navbar-right">
        @Html.Action("Index", "Advertising")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FileSharing/FileSharing/Views/Shared/_Moder.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
    <li>@Html.ActionLink("Загрузить", "Upload", "File")</li>
    <li>@Html.ActionLink("Скачать", "Download", "File")</li>
    <li>@Html.ActionLink("О сайте", "About", "Home")</li>
    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
    <li class="nav-item dropdown">
        <a class="navbar-link dropdown-toggle" href="#" id="navbarDropdownMenuListLink" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Списки
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>@Html.ActionLink("Список файлов", "Index", "File")</li>
            <li>@Html.ActionLink("Список категорий", "ListOfCategories", "Category")</li>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="navbar-link dropdown-toggle" href="#" id="navbarDropdownMenuAddLink" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Добавить
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>@Html.ActionLink("Файл", "Upload", "File")</li>
            <li>@Html.ActionLink("Категорию", "AddCategory", "Category")</li>
        </ul>
    </li>
</ul>

@using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Мой аккаунт", "AccountIndex", "Manage")</li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
}

FileSharing/FileSharing/Views/Shared/_User.cshtml
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
    <li>@Html.ActionLink("Загрузить", "Upload", "File")</li>
    <li>@Html.ActionLink("Скачать", "Download", "File")</li>
    <li>@Html.ActionLink("О сайте", "About", "Home")</li>
    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
</ul>

@using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Мой аккаунт", "AccountIndex", "Manage")</li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
}